version: '2'
services:
  jhipster68myblog-app:
    image: jhipster68myblog
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster68myblog-mysql:3306/jhipster68myblog?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jhipster68myblog-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhipster68myblog-elasticsearch:9200
    ports:
      - 8080:8080
  jhipster68myblog-mysql:
    extends:
      file: mysql.yml
      service: jhipster68myblog-mysql
  jhipster68myblog-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhipster68myblog-elasticsearch
